  <center><b><h1>Heart Disease</h1></b></center>
  <center><b><h1>Task - 2</h1></b></center>
  <center><b><h1>Karan Sonagara</h1></b></center>
     <center><b><h1>Enrollment -- 24010101694</h1></b></center>
         <center><b><h1>Rollno -- 138</h1></b></center>

#  Numpy  &  Perform Data Exploration with Pandas

-------------------------------------------------------------------------------
## Numpy

1) NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing.<br>
2) It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.<br>
3) NumPy is highly optimized and written in C, making it much faster than using regular Python lists for numerical operations.<br>
4) It serves as the foundation for many other Python libraries in data science and machine learning, like pandas, TensorFlow, and scikit-learn.<br>
5) With features like broadcasting, vectorization, and integration with C/C++ code, NumPy allows for cleaner and faster code in numerical computations.<br>



### Step 1. Import the Numpy library

In [2]:
import numpy as np



### Step 2. Create a 1D array of numbers

In [19]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

### Step 3. Reshape 1D to 2D Array

In [11]:
arr3 = np.arange(12).reshape(3, 4)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Step 4. Create a Linspace array

In [7]:
arr4 = np.linspace(1, 1, 5)
arr4

array([1., 1., 1., 1., 1.])

### Step 5. Create a Random Numbered Array

In [9]:
arr5 = np.random.rand(3, 4)
arr5

array([[0.17642223, 0.4339188 , 0.76623246, 0.24111004],
       [0.99867265, 0.65568381, 0.74620793, 0.42338742],
       [0.59718242, 0.44156543, 0.22621162, 0.85787908]])

### Step 6. Create a Random Integer Array

In [27]:
arr6 = np.random.randint(2, 10, 10)
arr6

array([5, 4, 8, 7, 3, 3, 5, 9, 2, 7])

### Step 7. Create a 1D Array and get Max,Min,ArgMax,ArgMin

In [29]:
arr6.argmin()

8

In [31]:
arr6.min()

2

In [33]:
arr6.max()

9

In [35]:
arr6.argmax()

7

### Step 8. Indexing in 1D Array

In [53]:
arr8 = np.array([1, 2, 3, 4, 5, 6 ,7, 8, 9 , 10])
arr8[:7:2]

array([1, 3, 5, 7])

### Step 9. Indexing in 2D Array

In [71]:
arr9 = np.arange(12).reshape(3, 4)
arr9

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
arr9[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [106]:
arr9

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
arr9[:3:2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

### Step 10. Conditional Selection

In [130]:
arr3 = np.arange(100)
arr3[arr3>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### 🔥You did it! 10 exercises down — you're on fire! 🔥

## Pandas



### Step 1. Import the necessary libraries

In [6]:
import pandas as pd

### Step 4. See the first 25 entries

In [8]:
df = pd.read_csv("Heart.csv",sep='|')
df.head(10)

age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0                 52,1,0,125,212,0,1,168,0,1,2,2,3,0                             
1               53,1,0,140,203,1,0,155,1,3.1,0,0,3,0                             
2               70,1,0,145,174,0,1,125,1,2.6,0,0,3,0                             
3                 61,1,0,148,203,0,1,161,0,0,2,1,3,0                             
4               62,0,0,138,294,1,1,106,0,1.9,1,3,2,0                             
5                 58,0,0,100,248,0,0,122,0,1,1,0,2,1                             
6               58,1,0,114,318,0,2,140,0,4.4,0,3,1,0                             
7               55,1,0,160,289,0,0,145,1,0.8,1,1,3,0                             
8               46,1,0,120,249,0,0,144,0,0.8,2,0,3,0                             
9               54,1,0,122,286,0,0,116,1,3.2,1,2,2,0

### Step 5. See the last 10 entries

In [10]:
df.tail(10)

age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
1015               58,1,0,128,216,0,0,131,1,2.2,1,3,3,0                             
1016               65,1,3,138,282,1,0,174,0,1.4,1,1,2,0                             
1017                  53,1,0,123,282,0,1,95,1,2,1,2,3,0                             
1018                 41,1,0,110,172,0,0,158,0,0,2,0,3,0                             
1019               47,1,0,112,204,0,1,143,0,0.1,2,0,2,1                             
1020                 59,1,1,140,221,0,1,164,1,0,2,0,2,1                             
1021               60,1,0,125,258,0,0,141,1,2.8,1,1,3,0                             
1022                 47,1,0,110,275,0,0,118,1,1,1,1,2,0                             
1023                 50,0,0,110,254,0,0,159,0,0,2,0,2,1                             
1024               54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

### Step 6. What is the number of observations in the dataset?

In [12]:
df.shape

(1025, 1)

### Step 7. What is the number of columns in the dataset?

In [14]:
df.count()

age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target    1025
dtype: int64

### Step 8. Print the name of all the columns.

In [16]:
df.columns

Index(['age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target'], dtype='object')

### Step 9. How is the dataset indexed?

In [18]:
df.index

RangeIndex(start=0, stop=1025, step=1)

### Step 10. What is the data type of each column?

In [20]:
df.dtypes

age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target    object
dtype: object

### Step 14. Summarize the DataFrame.

In [24]:
df.describe()

age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count                                                1025                             
unique                                                302                             
top                    38,1,2,138,175,0,1,173,0,0,2,4,2,1                             
freq                                                    8

### Step 15. Summarize all the columns

In [26]:
df.describe(include='all')

age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count                                                1025                             
unique                                                302                             
top                    38,1,2,138,175,0,1,173,0,0,2,4,2,1                             
freq                                                    8